### PR TITLE
added description, installation, and contributors to readme.md

### PR DESCRIPTION
**Pull request by Raparker88**
git fetch --all
git checkout rp-readMe

checkout read me file and add a list of your contributions under your name and push up the code.

### CODE REVIEW

**Review by ConnorBlakeney — APPROVED** [review]
thanks for doing this!

**Comment by heymonicakay** [comment]
Wonderful! Thanks!

**Review by heymonicakay — APPROVED** [review]
Two thumbs up!

**Review by samanthajmaas — COMMENTED** [review]
I added my contributions to the read me!

**Pull request merged**
